#!/bin/bash

# myOwnFirewall v0.1            
#
# Script para banear IPs
#
# Author: Rolando Caldas        
# http://rolandocaldas.com      
# 
# https://github.com/rolando-caldas/myOwnFirewall

BANNED_IPS="/etc/bloqueobloqueo/banlist.txt"
LOCK="/etc/bloqueobloqueo/.lock"

function banIP {
        if [ -f ${LOCK} ]
        then
                if [ $# -eq 0 ]
                then
                        echo "Debes ingresar una IP válida"
                else
                        ip=$1
                        exists=false
                        for i in `cat $BANNED_IPS`; do
                                if [ $i = $ip ]
                                then
                                        exists=true
                                fi
                        done

                        if [ $exists = false ]
                        then
                                echo $ip >> $BANNED_IPS
                                iptables -I INPUT -s $ip -j DROP
                                iptables -I OUTPUT -s $ip -j DROP
                                echo "IP ${ip} baneada"
                        else
                                echo "IP ${ip} ya en la lista"
                        fi
                fi
        else
                echo "BloqueoBloqueo no se está ejecutando"
    fi
}

function restartScript {
    stopScript
    startScript
}

function showHelp {
    echo "Uso: bloqueobloqueo {start|stop|restart}"
}

function startScript {

        if [ -f ${LOCK} ]
        then
                echo "BloqueoBloqueo ya se está ejecutando"
                exit
        else
                ` > ${LOCK}`

                for i in `cat $BANNED_IPS`; do
                        iptables -I INPUT -s $i -j DROP
                        iptables -I OUTPUT -s $i -j DROP
                done

                echo "BloqueoBloqueo iniciado"
        fi

}

function stopScript {
        if [ -f ${LOCK} ]
        then
                for i in `cat $BANNED_IPS`; do
                        iptables -D INPUT -s $i -j DROP
                        iptables -D OUTPUT -s $i -j DROP
                done
                rm ${LOCK}

                echo "BloqueoBloqueo detenido"
        else
                echo "BloqueoBloqueo no se está ejecutando"
        fi
}

function unbanIP {
        if [ -f ${LOCK} ]
        then
                if [ $# -eq 0 ]
                then
                        echo "Debes ingresar una dirección IP"
                else
                        ip=$1
                        exists=false

                        for i in `cat $BANNED_IPS`; do
                                if [ $i = $ip ]
                                then
                                        exists=true
                                else
                                        echo $i >> $TEMP
                                fi
                        done

                        if [ $exists = false ]
                        then
                                echo "IP ${ip} no está en la lista"
                        else
                                cp $TEMP $BANNED_IPS && rm $TEMP
                                iptables -D INPUT -s $ip -j DROP
                                iptables -D OUTPUT -s $ip -j DROP
                                echo "IP ${ip} desbloqueada"
                        fi
                fi
        else
                echo "BloqueoBloqueo no se está ejecutando"
        fi
}

case "$1" in
    ban)
        banIP $2
        exit
        ;;
    restart)
        restartScript
        exit
        ;;
    start)
        startScript
        exit
        ;;
    stop)
        stopScript
        exit
        ;;
    unban)
        unbanIP
        exit
        ;;
    *)
        showHelp
        exit
        ;;
esac

